### ISSUE TITLE
build fail when I try to use protoc-grpcio

### ISSUE THREAD

**Issue by Lynss** [mtp401/protoc-grpcio#17] opened 2019-03-29 13:30 UTC
sorry,my English isnt well,so I try to descript the problem I had 
**Describe the bug**
After read the Readme, I can generate throuth the first way Manual Generation with command 
`protoc --rust_out=. --grpc_out=. --plugin=protoc-gen-grpc=which grpc_rust_plugin example.proto.`
bug when I try to generate proto file by protoc-grpcio.cargo build fail
`failed to execute command: Permission denied (os error 13)`.
and the trace show that it panic at
```
        if self.always_configure || !build.join("CMakeCache.txt").exists() {
            run(cmd.env("CMAKE_PREFIX_PATH", cmake_prefix_path), "cmake");
        } else {
            println!("CMake project was already configured. Skipping configuration step.");
        }
```

```
fn run(cmd: &mut Command, program: &str) {
    println!("running: {:?}", cmd);
    let status = match cmd.status() {
        Ok(status) => status,
        Err(ref e) if e.kind() == ErrorKind::NotFound => {
            fail(&format!("failed to execute command: {}\nis `{}` not installed?",
                          e, program));
        }
        Err(e) => fail(&format!("failed to execute command: {}", e)),
    };
    if !status.success() {
        fail(&format!("command did not execute successfully, got: {}", status));
    }
}
```

**To Reproduce**
1.  clone the project protoc-grpcio
2. run the command `cargo run --manifest-path example/Cargo.toml --bin server`

**Expected behavior**
build fail and panic
`thread 'main' panicked at '
failed to execute command: Permission denied (os error 13)`

**System information**
* Ubuntu18.04
* libprotoc version 3.7.0
* cmake version 3.12.2
* rust 1.35-nightly
* go 1.11.5
* GNU ld (GNU Binutils) 2.32
* gcc 7.3.0

**Additional context**
- . - @mtp401

**Comment by mtp401** [comment] 2019-04-05 13:10
@Lynss can this be closed since the issue appears to be unrelated to this crate: https://github.com/pingcap/grpc-rs/issues/298#issuecomment-478727582?

**Comment by ice1000** [comment] 2019-04-07 03:15
He had mentioned that building grpcio directly is fine, the issue only occurs when using grpcio with this crate.
We can close after the answer popup.

(I cannot reproduce this issue. Weird)

**Comment by omac777** [comment] 2019-05-27 12:08
Lynss you may have "git clone" and "cargo build" of grpc and protoc-grpcio dir as user root,
then switched back to a non-root user when you started compiling/running the actual example.
That would give you "permission denied".

Try changing the ownership of the entire protoc-grpcio directory to the non-root user.
Then try cargo clean and cargo build after that.

**Comment by mtp401** [comment] 2019-06-18 12:41
Closing as unrelated https://github.com/pingcap/grpc-rs/issues/298#issuecomment-481656339

**Closed by mtp401** 2019-06-18 12:41 UTC
